// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChannelDetailRequest struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelDetailRequest) Reset()         { *m = ChannelDetailRequest{} }
func (m *ChannelDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ChannelDetailRequest) ProtoMessage()    {}
func (*ChannelDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_0b8e808446a1469d, []int{0}
}
func (m *ChannelDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelDetailRequest.Unmarshal(m, b)
}
func (m *ChannelDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelDetailRequest.Marshal(b, m, deterministic)
}
func (dst *ChannelDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelDetailRequest.Merge(dst, src)
}
func (m *ChannelDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ChannelDetailRequest.Size(m)
}
func (m *ChannelDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelDetailRequest proto.InternalMessageInfo

func (m *ChannelDetailRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type ChannelDetailResponse struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelDetailResponse) Reset()         { *m = ChannelDetailResponse{} }
func (m *ChannelDetailResponse) String() string { return proto.CompactTextString(m) }
func (*ChannelDetailResponse) ProtoMessage()    {}
func (*ChannelDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_0b8e808446a1469d, []int{1}
}
func (m *ChannelDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelDetailResponse.Unmarshal(m, b)
}
func (m *ChannelDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelDetailResponse.Marshal(b, m, deterministic)
}
func (dst *ChannelDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelDetailResponse.Merge(dst, src)
}
func (m *ChannelDetailResponse) XXX_Size() int {
	return xxx_messageInfo_ChannelDetailResponse.Size(m)
}
func (m *ChannelDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelDetailResponse proto.InternalMessageInfo

func (m *ChannelDetailResponse) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ChannelDetailResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChannelDetailResponse) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func init() {
	proto.RegisterType((*ChannelDetailRequest)(nil), "micro.account.ChannelDetailRequest")
	proto.RegisterType((*ChannelDetailResponse)(nil), "micro.account.ChannelDetailResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_0b8e808446a1469d) }

var fileDescriptor_account_0b8e808446a1469d = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcd, 0xcd, 0x4c, 0x2e, 0xca,
	0xd7, 0x83, 0x0a, 0x2a, 0x99, 0x70, 0x89, 0x38, 0x67, 0x24, 0xe6, 0xe5, 0xa5, 0xe6, 0xb8, 0xa4,
	0x96, 0x24, 0x66, 0xe6, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x70, 0x71, 0x26,
	0x43, 0xc4, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x4a, 0x89, 0x5c,
	0xa2, 0x68, 0xba, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xf1, 0x6b, 0x13, 0x12, 0xe2, 0x62, 0xc9,
	0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x02, 0x4b, 0x80, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0xf9, 0x45, 0x99,
	0xe9, 0x99, 0x79, 0x12, 0xcc, 0x60, 0x51, 0x28, 0xcf, 0x89, 0x33, 0x8a, 0x1d, 0xea, 0xc6, 0x24,
	0x36, 0xb0, 0xcb, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xd6, 0x7e, 0x83, 0xca, 0x00,
	0x00, 0x00,
}
